# Generated by Django 3.2.4 on 2021-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0003_auto_20210726_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Type_of_Purchase',
            field=models.IntegerField(default=0),
        ),
    ]
